### PR TITLE
Fixed countdown timer bug and some UI changes

### PR DESCRIPTION
**Pull request by vinaypuppal**
I was able to fix timer, the issue was with formatter 
http://hilios.github.io/jQuery.countdown/documentation.html#formatter

I used `%d Days left (taking away weeks)` that's why weeks disappeared while counting days 🤔

And now i tried `%D	 Total count of days till the end` which fixed the issue and now it shows correct no.of days.

I found one more [bug here](https://github.com/fcc-hyd/hackermonth/blob/f32b2b5bdfdeed52958830dd5a99f788ae15f9c4/meetup02/index.html#L77-L78) i.e in `meetup02/index.html` you referenced `timer.js` through incorrect path, fixed that also :smile:

### CODE REVIEW

**Comment by vinaypuppal** [comment]
- But later i realised, we don't need  `timer.js` in each meetup folder to pass meetup date, i modified `index.js` to accept meetup date as `data-attribute`.

- Since `.svg` is 5.7mb which is very large, so i converted it to `.png` and modified some css styles to fit for this banner image.

:point_right: For main `index.html` file 
whatsapp image 2016-11-25 at 1 50 01 am

:point_right: For meetup's `index.html` files (here i used it as background-image to get same look as main `index.html` file by introducing `banner-bg-img` class and the previous `banner` class behaviour is not modified so you can use anything that looks good )
whatsapp image 2016-11-25 at 2 20 03 am

**Comment by vinaypuppal** [comment]
- :tada: added icons to meetup links (I used [html utf symbols](http://www.w3schools.com/charsets/ref_utf_symbols.asp) as icons) instead of `icon-fonts` to save some bandwidth :wink:

image

**Comment by duttakapil** [comment]
Nice work! Really appreciate it :D

**Comment by vramana** [comment]
image
The UI is bit broken on 1920x1080 (my laptop resolution)

**Comment by vinaypuppal** [comment]
@vramana I fixed responsiveness in #4 but @duttakapil merged wrong commit. You can check my fork https://github.com/vinaypuppal/hackermonth/tree/main-timer and confirm if its looking good or not on your screen resolution.
I tested on [Screenfly](http://quirktools.com/screenfly/) its somewhat looking good since i did not target that screen resolution. But i can add another `media` query if needed.
image

**Pull request merged**
